engines:
  # Python
  pep8:
    enabled: true
  radon:
    enabled: true
  # Shell
  shellcheck:
    enabled: true
  # Web
  eslint:
    enabled: true
  # Misc.
  duplication:
    enabled: true

ratings:
  paths:
    - "**.py"
    - "**.sh"
    - "**.js"

# exclude generated, vendor and hidden files from code quality checks
exclude_paths:
  - "**/migrations/*"
  - "**/vendor/"
  - ".*"
