image: python:3.4

cache:
  paths:
  - ~/.cache/pip/

before_script:
  - pip install tox

test:
  script:
    # build docker image and push to registry
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker pull registry.gitlab.com/failmap/admin:staging
    - docker tag registry.gitlab.com/failmap/admin:staging registry.gitlab.com/failmap/admin:latest
    - docker push registry.gitlab.com/failmap/admin:latest

  only:
      - master
