stages:
  - test
  - build
  - staging
  - production

# functional testing
test: &test_template
  stage: test

  image: registry.gitlab.com/failmap/ci:latest

  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/pip-cache"
  cache:
    paths:
      - "$CI_PROJECT_DIR/pip-cache"
    key: "$CI_JOB_NAME"

  script:
    - tox -e test

  retry: 1

# functional testing using mysql database instead of sqlite
test_mysql: &test_mysql_template
  <<: *test_template
  services:
    - mysql:5.5
  variables:
    # configuration for docker mysql service
    MYSQL_ROOT_PASSWORD: failmap
    MYSQL_DATABASE: failmap
    MYSQL_USER: failmap
    MYSQL_PASSWORD: failmap
    # select mysql database settings, all settings default to 'failmap'
    # so they don't need to be passed explicitly
    DJANGO_DATABASE: production
    # add mysqlclient to tox environment
    TOX_EXTRAS: deploy
  retry: 1

# functional testing using postgres database instead of sqlite
test_postgres: &test_postgres_template
  <<: *test_template
  services:
    # current version in debian jessie
    - postgres:9.4
  variables:
    # configuration for docker mysql service
    POSTGRES_DB: failmap
    POSTGRES_USER: failmap
    POSTGRES_PASSWORD: failmap
    # select mysql database settings, all settings default to 'failmap'
    # so they don't need to be passed explicitly
    DJANGO_DATABASE: production
    DB_ENGINE: postgresql_psycopg2
    DB_HOST: postgres
    # add mysqlclient to tox environment
    TOX_EXTRAS: deploy

  # run long/non-critical tests only on master
  only: [master]
  retry: 1

# code quality checks
check:
  <<: *test_template
  stage: test

  script:
    - tox -e check
    - shellcheck tests/*.sh tools/*.sh

# integration tests
integration:
  <<: *test_template
  stage: test

  services:
    - redis:latest

  variables:
    BROKER: redis://redis:6379/0
    # required to run celery worker under docker 'root' user
    C_FORCE_ROOT: 1

  script:
    - tox -e integration

dataset:
  <<: *test_template
  script:
    - tox -e datasets

dataset_mysql:
  <<: *test_mysql_template
  script:
    - tox -e datasets
  # run long tests only on master
  only: [master]

dataset_postgres:
  <<: *test_postgres_template
  script:
    - tox -e datasets
  # run long tests only on master
  only: [master]

# create distributable release
build:
  stage: build

  services:
    - docker:dind

  variables:
    GIT_SUBMODULE_STRATEGY: recursive

  image: registry.gitlab.com/failmap/ci:docker-git

  before_script:
    # required for quering python package version
    - apk add --no-cache python3
    # login to docker and cache previous image if available
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker pull registry.gitlab.com/failmap/failmap:latest || true

  script:
    # store current version as artifact to copy into docker container
    - python3 setup.py --version > version

    # build docker image and push to registry
    - time docker build . --tag registry.gitlab.com/failmap/failmap:build
    - docker push registry.gitlab.com/failmap/failmap:build

    # push version tag to docker registry
    - docker tag registry.gitlab.com/failmap/failmap:build registry.gitlab.com/failmap/failmap:$(cat version|tr + _)
    - docker push registry.gitlab.com/failmap/failmap:$(cat version|tr + _)

  only:
    - master
    - tags
  retry: 1

# test building image & run image smoketest
image_test:
  stage: test

  services:
    - docker:dind

  image: registry.gitlab.com/failmap/ci:docker-git
  variables:
    TIMEOUT: 120
    GIT_SUBMODULE_STRATEGY: recursive

  before_script:
    # login to docker and cache previous image if available
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com

  script:
    # build docker image to test building
    - time docker build . --tag registry.gitlab.com/failmap/failmap:latest

    # run simple smoketests to verify Docker image is sane
    - time tests/docker.sh docker

    # run system tests against image
    - time tox -e system

  # run on merge request to determine if build will not break on master
  except: [master]
  retry: 1

# compare difference in build time between this and image_test without pull
image_test_with_pull:
  stage: test

  services:
    - docker:dind

  image: registry.gitlab.com/failmap/ci:docker-git
  variables:
    TIMEOUT: 120
    GIT_SUBMODULE_STRATEGY: recursive

  before_script:
    # login to docker and cache previous image if available
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker pull registry.gitlab.com/failmap/failmap:latest || true

  script:
    # build docker image to test building
    - time docker build . --tag registry.gitlab.com/failmap/failmap:latest

    # run simple smoketests to verify Docker image is sane
    - time tests/docker.sh docker

    # run system tests against image
    - time tox -e system

  # run on merge request to determine if build will not break on master
  except: [master]
  retry: 1

test_system:
  stage: staging

  image: registry.gitlab.com/failmap/ci:docker-git
  services:
  - docker:dind

  variables:
    IMAGE: registry.gitlab.com/failmap/failmap:build

  before_script:
    # login to docker and cache previous image if available
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com

  script:
    - time tox -e system

  only: [master]

staging:
  stage: staging

  image: registry.gitlab.com/failmap/ci:docker-git
  services:
  - docker:dind

  before_script:
    # login to docker and cache previous image if available
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com

  script:
    # store current version as artifact to copy into docker container
    - python3 setup.py --version > version
    - export tag=$(cat version|tr + _)

    # pull latest version and tag as staging
    - docker pull registry.gitlab.com/failmap/failmap:$tag
    - docker tag registry.gitlab.com/failmap/failmap:$tag registry.gitlab.com/failmap/failmap:staging

    # here is where I would put my staging integration tests, if I had one!!!

    # promote to staging after tests have succeeded
    - docker push registry.gitlab.com/failmap/failmap:staging

    # until there is a CD staging environment
    - docker tag registry.gitlab.com/failmap/failmap:$tag registry.gitlab.com/failmap/failmap:latest
    - docker push registry.gitlab.com/failmap/failmap:latest

  only: [master]
  retry: 1

production:
  stage: production

  image: registry.gitlab.com/failmap/ci:docker-git
  services:
  - docker:dind

  before_script:
    # login to docker and cache previous image if available
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com

  script:
    - export tag=$(git describe --exact-match --tags --abbrev=0)
    # build docker image and push to registry
    - docker pull registry.gitlab.com/failmap/failmap:$tag
    - docker tag registry.gitlab.com/failmap/failmap:$tag registry.gitlab.com/failmap/failmap:latest
    - docker push registry.gitlab.com/failmap/failmap:latest

    # insert deploy magic here

  only: [tags]
  retry: 1
