language: python
python:
  - 3.4

install: pip install tox-travis codeclimate-test-reporter

script: tox

after_success:
  - coveralls
  - CODECLIMATE_REPO_TOKEN=4bd7b6de99845dea19ae759dd9021a652198cc89c7003a562045ece83ae541bd codeclimate-test-reporter
