language: python
python:
  - 3.4

install: pip install tox-travis codeclimate-test-reporter

script: tox

after_success:
  - coveralls
  # - CODECLIMATE_REPO_TOKEN=e94e70f9013dce55ec6649577c839054b2236c00 codeclimate-test-reporter
