[tool.pytest.ini_options]
minversion = "6.0"
python_files = ["tests.py", "test_*.py", "*_tests.py"]
testpaths = [
    "tests",
    "websecmap",
]
norecursedirs = ["*fixtures*", "*locale*", "*migrations*", "*static*"]
log_cli = true

